### ISSUE TITLE
Blueprint doesn't run with Shipyard 0.1.18

### ISSUE THREAD

**Issue by onematchfox** [nicholasjackson/consul-smi-controller#1]
Disclaimer: Complete noob to shipyard in general. I also understand this work is perhaps not something you expected people to be playing around with :)

Anyway.... I wanted to give this blueprint a quick spin but it seems to make use of a number of resources/attributes which are incompatible with shipyard v0.1.18. 

To begin with I can't find information on the `ingress` resources in the shipyard docs. These fail to _run_ with errors like:
`consul-smi-controller/blueprint/modules/consul/consul.hcl:17,18-18: Missing required argument; The argument "target" is required, but no definition was found., and 2 other diagnostic(s)` 

I figured I'd try converting the `ingress` to `k8s_ingress` resources to get past that error which then led to issues with the `helm` resources use of `create_namespace` ala `consul-smi-controller/blueprint/modules/smi-controller/controller.hcl:6,3-19: Unsupported argument; An argument named "create_namespace" is not expected here.` 

Given that this attempt is beginning to feel like playing whac-a-mole I've decided to step back and assume I'm doing something very obviously wrong. Hoping you might be able to point me in the right direction?

**Comment by nicholasjackson** [comment]
Hey @onematchfox I totally apologize, I have been dogfooding a new feature of shipyard while building this controller which allows you to proxy traffic from a kubernetes cluster to your local machine. This allows the Kubernetes API to call the conversion webhooks of your locally running service.

However, I have not yet merged this into the main Shipyard, the docs are done, code, complete, I just need to release it. Let me do that this afternoon. Again sorry about this.

**Comment by onematchfox** [comment]
No need for apologies. Thanks for the confirmation that it wasn't just me being an idiot :relieved: And no hurry on getting the new version out - I'll watch for it when it comes.
